ALTER TABLE tool_definition ADD COLUMN IF NOT EXISTS mcp_server_url TEXT;
ALTER TABLE tool_definition ADD COLUMN IF NOT EXISTS mcp_transport VARCHAR(32) NOT NULL DEFAULT 'STREAMABLE_HTTP';
ALTER TABLE tool_definition ADD COLUMN IF NOT EXISTS mcp_auth_env VARCHAR(160);
